Bacillus subtilis:
  title: Bacillus subtilis

Clostridium acetobutylicum:
  title: Clostridium acetobutylicum

Escherichia coli:
  title: Escherichia coli

Lactic Acid Bacteria:
  title: Lactic Acid Bacteria

Lactococcus lactis:
  title: Lactococcus lactis

Enterococcus faecalis:
  title: Enterococcus faecalis

Streptococcus pyogenes:
  title: Streptococcus pyogenes

Pseudomonas putida:
  title: Pseudomonas putida

Pseudomonas fluorescens:
  title: Pseudomonas fluorescens

Saccharomyces cerevisiae:
  title: Saccharomyces cerevisiae

Streptomyces coelicolor:
  title: Streptomyces coelicolor

Sulfolobus solfataricus:
  title: Sulfolobus solfataricus

Trypanosoma brucei:
  title: Trypanosoma brucei

Lactobacillus plantarum:
  title: Lactobacillus plantarum