K-12/MG1655:
  id: 1
  organism: Escherichia coli
  title: K-12/MG1655

MC4100:
  id: 2
  organism: Escherichia coli
  title: MC4100

168:
  id: 3
  organism: Bacillus subtilis
  title: 168

NCIB3610:
  id: 4
  organism: Bacillus subtilis
  title: NCIB3610

JW49:
  id: 5
  organism: Bacillus subtilis
  title: JW49

ATCC6633:
  id: 6
  organism: Bacillus subtilis
  title: ATCC6633

V583:
  id: 7
  organism: Enterococcus faecalis
  title: V583

ATCC29200:
  id: 8
  organism: Enterococcus faecalis
  title: ATCC29200

DS5:
  id: 9
  organism: Enterococcus faecalis
  title: DS5

TX0012:
  id: 10
  organism: Enterococcus faecalis
  title: TX0012

M49(591):
  id: 11
  organism: Streptococcus pyogenes
  title: M49 (591)

ATCC824:
  id: 12
  organism: Clostridium acetobutylicum
  title: ATCC824

NCIMB8052:
  id: 13
  organism: Clostridium acetobutylicum
  title: NCIMB8052

DOTT1:
  id: 14
  organism: Pseudomonas putida
  title: DOT-T1

NCIMB10525:
  id: 15
  organism: Pseudomonas fluorescens
  title: NCIMB10525

A3(2):
  id: 16
  organism: Streptomyces coelicolor
  title: A3(2)

M145:
  id: 17
  organism: Streptomyces coelicolor
  title: M145

P2:
  id: 18
  organism: Sulfolobus solfataricus
  title: P2

YJM789:
  id: 19
  organism: Saccharomyces cerevisiae
  title: YJM789

FY2:
  id: 20
  organism: Saccharomyces cerevisiae
  title: FY2 diploid

FY3:
  id: 21
  organism: Saccharomyces cerevisiae
  title: FY3 diploid

YSBN1:
  id: 22
  organism: Saccharomyces cerevisiae
  title: YSBN1 diploid

YSBN2:
  id: 23
  organism: Saccharomyces cerevisiae
  title: YSBN2 diploid

CENPK113-7D:
  id: 24
  organism: Saccharomyces cerevisiae
  title: CEN.PK113-7D haploid

BY4741:
  id: 25
  organism: Saccharomyces cerevisiae
  title: BY4741


