technology:
  title: technology
  children: binding,chromatography, culture_growth,electrophoresis,imaging,Mass_Spectrometry,microarray,PCR,structural_methods

binding:
  title: binding
  children: 2-hybrid_system,surface_plasmon_resonance

2-hybrid_system:
  title: 2-hybrid system

surface_plasmon_resonance:
  title: surface plasmon resonance

chromatography:
  title: chromatography
  children: gas_chromatography,HPLC,UPLC

gas_chromatography:
  title: gas chromatography

HPLC:
  title: HPLC

UPLC:
  title: UPLC

electrophoresis:
  title: electrophoresis
  children: capillary_electrophoresis,gel_electrophoresis

capillary_electrophoresis:
  title: capillary electrophoresis

gel_electrophoresis:
  title: gel electrophoresis
  children: 2D_gel_electrophoresis,SDS_PAGE

2D_gel_electrophoresis:
  title: 2D gel electrophoresis
  
SDS_PAGE:
  title: SDS PAGE

imaging:
  title: imaging
  children: FRAP

FRAP:
  title: FRAP

Mass_Spectrometry:
  title: mass spectrometry
  children: Accelerator_Mass_Spectrometry,Gas_Chromatography_Mass_Spectrometry,Inductively_Coupled_Plasma_Mass_Spectrometry,Ion_Mobility_Spectrometry_Mass_Spectrometry,Isotope_Ratio_Mass_Spectrometry,liquid_chromatography-tandem_mass_spectrometry,liquid_chromatography_Mass_Spectrometry,MALDI_TOF,SELDI_TOF,Tandem_Mass_Spectrometry

Accelerator_Mass_Spectrometry:
  title: accelerator mass spectrometry

Gas_Chromatography_Mass_Spectrometry:
  title: gas chromatography mass spectrometry

Inductively_Coupled_Plasma_Mass_Spectrometry:
  title: inductively coupled plasma mass spectrometry

Ion_Mobility_Spectrometry_Mass_Spectrometry:
  title: ion mobility spectrometry mass spectrometry

Isotope_Ratio_Mass_Spectrometry:
  title: isotope ratio mass spectrometry

liquid_chromatography-tandem_mass_spectrometry:
  title: liquid chromatography-tandem mass spectrometry

liquid_chromatography_Mass_Spectrometry:
  title: liquid chromatography mass spectrometry

MALDI_TOF:
  title: MALDI TOF

SELDI_TOF:
  title: SELDI TOF

Tandem_Mass_Spectrometry:
  title: tandem mass spectrometry


microarray:
  title: microarray
  children: cDNA_microarray,ChIP-on-chip,custom_Array,DNA_Methylation,miRNA_microarray

cDNA_microarray:
  title: cDNA microarray

ChIP-on-chip:
  title: ChIP-on-chip

custom_Array:
  title: custom array

DNA_Methylation:
  title: DNA methylation

miRNA_microarray:
  title: miRNA microarray

PCR:
  title: PCR
  children: qPCR,qRT-PCR

qPCR:
  title: qPCR

qRT-PCR:
  title: qRT-PCR


structural_methods:
  title: structural methods
  children: NMR

NMR:
  title: NMR