#MySQL
development:
  adapter: mysql
  database: seek_development
  username: mysqluser
  password: mysqlpassword
  #socket: /var/run/mysqld/mysqld.sock 

test:
  adapter: mysql
  database: seek_test
  username: mysqluser
  password: mysqlpassword
  #socket: /var/run/mysqld/mysqld.sock 

production:
  adapter: mysql
  database: seek_production
  username: mysqluser
  password: mysqlpassword

# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  timeout: 5000 

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  timeout: 5000
#
#production:
#  adapter: sqlite3
#  database: db/production.sqlite3
#  timeout: 5000
