#Database configuration for cruise control
#development:
#  adapter: mysql
#  database: seek_development_cc
#  username: mysqluser
#  password: mysqluser
#  #socket: /var/run/mysqld/mysqld.sock 
#
#test:
#  adapter: mysql
#  database: seekhub_test_cc
#  username: mysqluser
#  password: mysqluser
#  #socket: /var/run/mysqld/mysqld.sock 
#
#production:
#  adapter: mysql
#  database: seekhub_production_cc
#  #database: seekhub_development
#  username: mysqluser
#  password: mysqluser

development:
    adapter: sqlite3
    database: db/dev.sqlite3
    
production:
    adapter: sqlite3
    database: db/prod.sqlite3
        
test:
    adapter: sqlite3
    database: db/test.sqlite3
